CREATE TABLE T_TASK_STATUS (
	TASK_STATUS_OID  INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   
    TASK_STATUS      VARCHAR(32)
);
ALTER TABLE T_TASK_STATUS ADD CONSTRAINT U_TASK_STATUS UNIQUE (TASK_STATUS);


CREATE TABLE T_TASK (
	TASK_OID      INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   
    TASK_UUID     CHAR(36),
    TASK_VERSION  INT,   
    TASK_NAME     VARCHAR(256),   
	TASK_DESC     VARCHAR(1024),   
	TASK_STATUS   VARCHAR(32)
);
ALTER TABLE T_TASK ADD CONSTRAINT U_TASK_UUID UNIQUE (TASK_UUID);
ALTER TABLE T_TASK ADD CONSTRAINT U_TASK_NAME UNIQUE (TASK_NAME);
ALTER TABLE T_TASK ADD FOREIGN KEY (TASK_STATUS) REFERENCES T_TASK_STATUS(TASK_STATUS);


CREATE TABLE T_TAG (
	TAG_OID      INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   
    TAG_VERSION  INT,   
    TAG_NAME     VARCHAR(256)   
);
ALTER TABLE T_TAG ADD CONSTRAINT U_TAG_NAME UNIQUE (TAG_NAME);

CREATE TABLE T_TASK_TAG (
    TASK_OID  INT,
    TAG_OID   INT
);
ALTER TABLE T_TASK_TAG ADD FOREIGN KEY (TASK_OID) REFERENCES T_TASK(TASK_OID);
ALTER TABLE T_TASK_TAG ADD FOREIGN KEY (TAG_OID) REFERENCES T_TAG(TAG_OID);
